export default [
  // core
  // 'WindowProxy.webidl',
  'Location.webidl',
  'Event.webidl',
  'EventTarget.webidl',
  'NodeFilter.webidl',
  'DOMRect.webidl',
  'DOMRectList.webidl',
  'DOMException.webidl',
  // 'HTMLFormControlsCollection.webidl',
  // 'CanvasRendering.webidl',
  // 'WebGLRendering.webidl',
  // 'DOMMatrix.webidl',
  // 'DOMPoint.webidl',
  'OffscreenCanvas.webidl',
  // 'ImageBitmap.webidl',

  // attributes
  'attributes/Attr.webidl',
  'attributes/NamedNodeMap.webidl',

  // animation
  'animation/Animatable.webidl',
  'animation/Animation.webidl',
  'animation/AnimationEffect.webidl',

  // css
  'css/CSSStyleDeclaration.webidl',
  'css/CSSRule.webidl',
  'css/CSSStyleSheet.webidl',
  'css/CSSRuleList.webidl',
  'css/StyleSheet.webidl',
  'css/MediaList.webidl',
  'css/CSSStyleValue.webidl',
  'css/StylePropertyMap.webidl',

  // domparsing
  'domparsing/DOMParser.webidl',
  'domparsing/XMLSerializer.webidl',

  // files
  'files/Blob.webidl',
  'files/File.webidl',
  'files/FileList.webidl',
  // 'files/FileReader.webidl',

  // fetch
  // 'fetch/Fetch.webidl',
  // 'fetch/FormData.webidl',
  'fetch/ReferrerPolicy.webidl',

  // events
  'events/GlobalEventHandlers.webidl',
  'events/DocumentAndElementEventHandlers.webidl',

  // nodes
  'nodes/CDATASection.webidl',
  'nodes/CharacterData.webidl',
  'nodes/ChildNode.webidl',
  'nodes/Comment.webidl',
  'nodes/Document.webidl',
  'nodes/DocumentFragment.webidl',
  'nodes/DocumentOrShadowRoot.webidl',
  'nodes/DocumentType.webidl',
  'nodes/DOMImplementation.webidl',
  'nodes/DOMStringMap.webidl',
  'nodes/DOMTokenList.webidl',
  'nodes/Element.webidl',
  'nodes/ElementContentEditable.webidl',
  'nodes/ElementCSSInlineStyle.webidl',
  'nodes/HTMLAnchorElement.webidl',
  'nodes/HTMLAreaElement.webidl',
  'nodes/HTMLAudioElement.webidl',
  'nodes/HTMLBaseElement.webidl',
  'nodes/HTMLBodyElement.webidl',
  'nodes/HTMLBRElement.webidl',
  'nodes/HTMLButtonElement.webidl',
  'nodes/HTMLCanvasElement.webidl',
  // 'nodes/HTMLCollection.webidl',
  'nodes/HTMLDataElement.webidl',
  'nodes/HTMLDataListElement.webidl',
  'nodes/HTMLDetailsElement.webidl',
  'nodes/HTMLDialogElement.webidl',
  'nodes/HTMLDirectoryElement.webidl',
  'nodes/HTMLDivElement.webidl',
  'nodes/HTMLDListElement.webidl',
  'nodes/HTMLElement.webidl',
  'nodes/HTMLEmbedElement.webidl',
  'nodes/HTMLFieldSetElement.webidl',
  'nodes/HTMLFontElement.webidl',
  'nodes/HTMLFormElement.webidl',
  'nodes/HTMLFrameElement.webidl',
  'nodes/HTMLFrameSetElement.webidl',
  'nodes/HTMLHeadElement.webidl',
  'nodes/HTMLHeadingElement.webidl',
  'nodes/HTMLHRElement.webidl',
  'nodes/HTMLHtmlElement.webidl',
  'nodes/HTMLHyperlinkElementUtils.webidl',
  'nodes/HTMLIFrameElement.webidl',
  'nodes/HTMLImageElement.webidl',
  'nodes/HTMLInputElement.webidl',
  'nodes/HTMLLabelElement.webidl',
  'nodes/HTMLLegendElement.webidl',
  'nodes/HTMLLIElement.webidl',
  'nodes/HTMLLinkElement.webidl',
  'nodes/HTMLMapElement.webidl',
  'nodes/HTMLMarqueeElement.webidl',
  'nodes/HTMLMediaElement.webidl',
  'nodes/HTMLMenuElement.webidl',
  'nodes/HTMLMetaElement.webidl',
  'nodes/HTMLMeterElement.webidl',
  'nodes/HTMLModElement.webidl',
  'nodes/HTMLObjectElement.webidl',
  'nodes/HTMLOListElement.webidl',
  'nodes/HTMLOptGroupElement.webidl',
  'nodes/HTMLOptionElement.webidl',
  'nodes/HTMLOptionsCollection.webidl',
  'nodes/HTMLOrSVGElement.webidl',
  'nodes/HTMLOutputElement.webidl',
  'nodes/HTMLParagraphElement.webidl',
  'nodes/HTMLParamElement.webidl',
  'nodes/HTMLPictureElement.webidl',
  'nodes/HTMLPreElement.webidl',
  'nodes/HTMLProgressElement.webidl',
  'nodes/HTMLQuoteElement.webidl',
  'nodes/HTMLScriptElement.webidl',
  'nodes/HTMLSelectElement.webidl',
  'nodes/HTMLSlotElement.webidl',
  'nodes/HTMLSourceElement.webidl',
  'nodes/HTMLSpanElement.webidl',
  'nodes/HTMLStyleElement.webidl',
  'nodes/HTMLTableCaptionElement.webidl',
  'nodes/HTMLTableCellElement.webidl',
  'nodes/HTMLTableColElement.webidl',
  'nodes/HTMLTableElement.webidl',
  'nodes/HTMLTableRowElement.webidl',
  'nodes/HTMLTableSectionElement.webidl',
  'nodes/HTMLTemplateElement.webidl',
  'nodes/HTMLTextAreaElement.webidl',
  'nodes/HTMLTimeElement.webidl',
  'nodes/HTMLTitleElement.webidl',
  'nodes/HTMLTrackElement.webidl',
  'nodes/HTMLUListElement.webidl',
  'nodes/HTMLUnknownElement.webidl',
  'nodes/HTMLVideoElement.webidl',
  'nodes/LinkStyle.webidl',
  'nodes/Node.webidl',
  'nodes/NodeList.webidl',
  'nodes/NonDocumentTypeChildNode.webidl',
  'nodes/NonElementParentNode.webidl',
  'nodes/ParentNode.webidl',
  'nodes/ProcessingInstruction.webidl',
  'nodes/ShadowRoot.webidl',
  'nodes/Slotable.webidl',
  'nodes/SVGElement.webidl',
  'nodes/SVGGraphicsElement.webidl',
  'nodes/SVGSVGElement.webidl',
  'nodes/SVGTests.webidl',
  'nodes/SVGTitleElement.webidl',
  'nodes/Text.webidl',
  'nodes/WindowEventHandlers.webidl',
  'nodes/XMLDocument.webidl',

  // range
  'range/AbstractRange.webidl',
  'range/Range.webidl',
  // 'range/StaticRange.webidl',

  // selection
  'selection/Selection.webidl',

  // svg
  // 'svg/SVGAnimatedString.webidl',
  'svg/SVGNumber.webidl',
  'svg/SVGStringList.webidl',

  // traversal
  'traversal/NodeIterator.webidl',
  'traversal/TreeWalker.webidl',

  // validation
  'validation/ValidityState.webidl',

  // fonts
  'fonts/FontFaceSet.webidl',
  'fonts/FontFace.webidl',

  // misc
  'Fullscreen.webidl',
  'FeaturePolicy.webidl',

  // xpath
  'xpath/XPathEvaluator.webidl',
  'xpath/XPathEvaluatorBase.webidl',
  'xpath/XPathExpression.webidl',
  'xpath/XPathResult.webidl',
];
